const API='http://localhost:8080';
const state={login:{recorder:null,chunks:[],blob:null,recording:false,timer:null,elapsed:0},register:{recorder:null,chunks:[],blob:null,recording:false,timer:null,elapsed:0}};
const MAX_SECONDS=6;
(function(){const c=document.getElementById('particles');for(let i=0;i<30;i++){const p=document.createElement('div');p.className='particle';p.style.cssText=`left:${Math.random()*100}%;bottom:${Math.random()*-20}%;animation-duration:${4+Math.random()*8}s;animation-delay:${Math.random()*6}s;width:${1+Math.random()*2}px;height:${1+Math.random()*2}px;`;c.appendChild(p);}})();
function setMode(m){document.getElementById('sectionLogin').classList.toggle('hidden',m!=='login');document.getElementById('sectionRegister').classList.toggle('hidden',m!=='register');document.getElementById('btnLogin').classList.toggle('active',m==='login');document.getElementById('btnRegister').classList.toggle('active',m==='register');}
async function toggleRecord(m){state[m].recording?stopRecording(m):await startRecording(m);}
async function startRecording(m){const s=state[m];try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});s.chunks=[];s.blob=null;s.elapsed=0;s.recorder=new MediaRecorder(stream,{mimeType:'audio/webm'});s.recorder.ondataavailable=e=>{if(e.data.size>0)s.chunks.push(e.data);};s.recorder.onstop=()=>{s.blob=new Blob(s.chunks,{type:'audio/webm'});stream.getTracks().forEach(t=>t.stop());onDone(m);};s.recorder.start(100);s.recording=true;setUI(m,true);drawWave(m,stream);s.timer=setInterval(()=>{s.elapsed+=.1;updateRing(m,s.elapsed/MAX_SECONDS);if(s.elapsed>=MAX_SECONDS)stopRecording(m);},100);}catch(err){setStatus(m,'❌ Microphone access denied. Allow mic in browser settings.','red');}}
function stopRecording(m){const s=state[m];if(!s.recording)return;s.recording=false;clearInterval(s.timer);if(s.recorder&&s.recorder.state!=='inactive')s.recorder.stop();setUI(m,false);}
function onDone(m){setStatus(m,`✅ ${state[m].elapsed.toFixed(1)}s recorded — ready to submit`,'green');document.getElementById(m+'MicBtn').classList.add('recorded');document.getElementById(m==='login'?'loginSubmit':'registerSubmit').disabled=false;updateRing(m,1);}
function drawWave(m,stream){const canvas=document.getElementById(m+'Wave');canvas.style.display='block';const ctx=canvas.getContext('2d'),ac=new AudioContext(),src=ac.createMediaStreamSource(stream),ana=ac.createAnalyser();ana.fftSize=64;src.connect(ana);const data=new Uint8Array(ana.frequencyBinCount);function draw(){if(!state[m].recording){ctx.clearRect(0,0,canvas.width,canvas.height);return;}requestAnimationFrame(draw);ana.getByteFrequencyData(data);canvas.width=canvas.clientWidth;canvas.height=40;ctx.clearRect(0,0,canvas.width,canvas.height);const bw=canvas.width/data.length;data.forEach((v,i)=>{const h=(v/255)*canvas.height,g=ctx.createLinearGradient(0,canvas.height-h,0,canvas.height);g.addColorStop(0,'#00e5a0');g.addColorStop(1,'#00e5a030');ctx.fillStyle=g;ctx.fillRect(i*bw,canvas.height-h,bw-1,h);});}draw();}
function updateRing(m,pct){document.getElementById(m+'RingFill').style.strokeDashoffset=339.3*(1-Math.min(pct,1));}
function setUI(m,rec){const btn=document.getElementById(m+'MicBtn');btn.classList.toggle('recording',rec);btn.classList.remove('recorded');btn.querySelector('.mic-icon').textContent=rec?'⏹️':'🎙️';if(rec)setStatus(m,'🔴 Recording… speak clearly','red');}
function setStatus(m,t,c='muted'){const el=document.getElementById(m+'Status');el.textContent=t;el.style.color=c==='green'?'var(--green)':c==='red'?'var(--red)':'var(--muted)';}
function setResult(m,html){document.getElementById(m+'Result').innerHTML=html;}
async function submitLogin(){const username=document.getElementById('loginUsername').value.trim().toLowerCase(),blob=state.login.blob;if(!username){setResult('login',err('Please enter your username.'));return;}if(!blob){setResult('login',err('Please record your voice first.'));return;}const btn=document.getElementById('loginSubmit');btn.disabled=true;btn.innerHTML='<span class="spinner"></span>VERIFYING…';const fd=new FormData();fd.append('username',username);fd.append('audio',blob,'voice.webm');try{const res=await fetch(`${API}/login`,{method:'POST',body:fd}),data=await res.json();if(data.matched){localStorage.setItem('vg_token',data.token);localStorage.setItem('vg_user',data.username);localStorage.setItem('vg_display',data.display_name);setResult('login',`<div class="result-card success"><div class="verdict">✅ VOICE VERIFIED</div><div class="sub">Welcome back, ${data.display_name} · Match: ${data.confidence}%</div><div class="conf-bar"><div class="conf-fill" style="width:${data.confidence}%"></div></div></div>`);setTimeout(()=>{window.location.href='index.html';},1200);}else{setResult('login',err(data.error||'Voice not recognised. Try again.',data.confidence||0));btn.disabled=false;btn.textContent='VERIFY VOICE';}}catch(e){setResult('login',err('Cannot reach server. Is Flask running on port 8080?'));btn.disabled=false;btn.textContent='VERIFY VOICE';}}
async function submitRegister(){const username=document.getElementById('regUsername').value.trim().toLowerCase(),displayName=document.getElementById('regDisplayName').value.trim(),blob=state.register.blob;if(!username){setResult('register',err('Please enter a username.'));return;}if(!blob){setResult('register',err('Please record your voice first.'));return;}const btn=document.getElementById('registerSubmit');btn.disabled=true;btn.innerHTML='<span class="spinner"></span>REGISTERING…';const fd=new FormData();fd.append('username',username);fd.append('display_name',displayName||username);fd.append('audio',blob,'voice.webm');try{const res=await fetch(`${API}/register`,{method:'POST',body:fd}),data=await res.json();if(data.success){localStorage.setItem('vg_token',data.token);localStorage.setItem('vg_user',data.username);localStorage.setItem('vg_display',data.display_name);setResult('register',`<div class="result-card success"><div class="verdict">✅ VOICE REGISTERED</div><div class="sub">${data.message}</div><div class="conf-bar"><div class="conf-fill" style="width:100%"></div></div></div>`);setTimeout(()=>{window.location.href='index.html';},1400);}else{setResult('register',err(data.error||'Registration failed.'));btn.disabled=false;btn.textContent='REGISTER VOICE';}}catch(e){setResult('register',err('Cannot reach server. Is Flask running on port 8080?'));btn.disabled=false;btn.textContent='REGISTER VOICE';}}
function err(msg,conf=0){return `<div class="result-card error"><div class="verdict">❌ ${msg}</div>${conf?`<div class="conf-bar"><div class="conf-fill" style="width:${conf}%"></div></div>`:''}</div>`;}
if(localStorage.getItem('vg_token'))window.location.href='index.html';
