const API='http://localhost:8080';
const TOKEN=localStorage.getItem('vg_token'),DISPLAY=localStorage.getItem('vg_display')||'User',UNAME=localStorage.getItem('vg_user')||'';
if(!TOKEN)window.location.href='login.html';
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('userLabel').textContent=DISPLAY;loadStats();setInterval(loadStats,12000);});
function logout(){fetch(`${API}/logout`,{method:'POST',headers:{'X-Token':TOKEN}}).finally(()=>{localStorage.clear();window.location.href='login.html';});}
function authH(){return{'X-Token':TOKEN};}
function switchTab(n,btn){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));document.getElementById('panel-'+n).classList.add('active');btn.classList.add('active');if(n==='history')loadHistory();}
async function loadStats(){try{const r=await fetch(`${API}/stats`,{headers:authH()}),d=await r.json();animateNum('statScans',d.total_scans);animateNum('statFlagged',d.flagged);animateNum('statAuth',d.authenticated);animateNum('statProtected',d.protected);}catch(_){}}
function animateNum(id,target){const el=document.getElementById(id),cur=parseInt(el.textContent)||0;if(cur===target)return;const step=Math.ceil(Math.abs(target-cur)/14);let v=cur;const t=setInterval(()=>{v=v<target?Math.min(v+step,target):Math.max(v-step,target);el.textContent=v;if(v===target)clearInterval(t);},40);}
function onFileChosen(iid,lid,bid,cid){const file=document.getElementById(iid).files[0];if(!file)return;const l=document.getElementById(lid);l.style.display='block';l.textContent='📁 '+file.name;document.getElementById(bid).disabled=false;drawStaticWave(file,cid);}
function drawStaticWave(file,cid){const canvas=document.getElementById(cid);if(!canvas)return;canvas.parentElement.style.display='block';const r=new FileReader();r.onload=e=>{try{const ac=new(window.AudioContext||window.webkitAudioContext)();ac.decodeAudioData(e.target.result,buf=>{const data=buf.getChannelData(0),step=Math.floor(data.length/canvas.clientWidth),ctx=canvas.getContext('2d');canvas.width=canvas.clientWidth;canvas.height=56;ctx.clearRect(0,0,canvas.width,canvas.height);for(let i=0;i<canvas.width;i++){const sl=data.slice(i*step,(i+1)*step),mx=Math.max(...sl.map(Math.abs)),h=mx*canvas.height,g=ctx.createLinearGradient(0,canvas.height/2-h/2,0,canvas.height/2+h/2);g.addColorStop(0,'#00e5a0');g.addColorStop(1,'#00e5a050');ctx.fillStyle=g;ctx.fillRect(i,(canvas.height-h)/2,1,h||1);}});}catch(_){}};r.readAsArrayBuffer(file);}
function handleDragOver(e,z){e.preventDefault();document.getElementById(z).classList.add('dragover');}
function handleDragLeave(z){document.getElementById(z).classList.remove('dragover');}
function handleDrop(e,i,z){e.preventDefault();document.getElementById(z).classList.remove('dragover');if(!e.dataTransfer.files.length)return;const inp=document.getElementById(i),dT=new DataTransfer();dT.items.add(e.dataTransfer.files[0]);inp.files=dT.files;inp.dispatchEvent(new Event('change'));}
let lastResult={};
async function runDetect(blob=null){const file=blob||document.getElementById('detectInput').files[0];if(!file)return;setLoading('detect',true);document.getElementById('detectResult').style.display='none';const fd=new FormData();fd.append('audio',file,file.name||'recording.webm');try{const res=await fetch(`${API}/detect`,{method:'POST',body:fd,headers:authH()}),d=await res.json();lastResult={...d,filename:file.name||'recorded_audio'};showResult(d,'detectResult');loadStats();}catch(_){showToast('❌ Cannot reach backend. Is Flask running on port 8080?');}finally{setLoading('detect',false);}}
function showResult(d,cid){const card=document.getElementById(cid);card.className=`result-card ${d.color||'yellow'}`;card.style.display='block';if(cid==='detectResult'){document.getElementById('rIcon').textContent=d.authenticated?'✅':'❌';document.getElementById('rVerdict').textContent=d.verdict||'—';document.getElementById('rRiskLabel').textContent=d.risk_label||'';document.getElementById('rRisk').textContent=(d.risk||'—')+' RISK';document.getElementById('rConf').textContent=(d.confidence||0)+'%';document.getElementById('rFile').textContent=d.filename||'—';document.getElementById('rDuration').textContent=d.duration_seconds?d.duration_seconds+'s':'—';document.getElementById('rScore').textContent=d.score!==undefined?d.score:'—';setTimeout(()=>{document.getElementById('rConfFill').style.width=(d.confidence||0)+'%';},60);}else{card.innerHTML=`<div class="verdict-row"><div class="verdict-badge"><div class="vicon">${d.authenticated?'✅':'❌'}</div><div class="vtext"><h2>${d.verdict||'—'}</h2><p>${d.risk_label||''}</p></div></div><div class="risk-pill">${d.risk||'—'} RISK</div></div><div class="conf-section"><div class="conf-labels"><span>CONFIDENCE</span><span>${d.confidence||0}%</span></div><div class="conf-track"><div class="conf-fill" id="rcFill"></div></div></div>`;setTimeout(()=>{const f=document.getElementById('rcFill');if(f)f.style.width=(d.confidence||0)+'%';},60);}}
async function runProtect(blob=null){const file=blob||document.getElementById('protectInput').files[0];if(!file)return;setLoading('protect',true);document.getElementById('protectSuccess').style.display='none';const fd=new FormData();fd.append('audio',file,file.name||'recording.webm');try{const res=await fetch(`${API}/embed`,{method:'POST',body:fd,headers:authH()});if(!res.ok){const err=await res.json();showToast('❌ '+(err.error||'Embed failed'));return;}const blob2=await res.blob(),url=URL.createObjectURL(blob2),a=document.createElement('a');a.href=url;a.download='watermarked_'+(file.name||'audio').replace(/\.[^.]+$/,'')+'.wav';document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(url);document.getElementById('protectSuccess').style.display='block';document.getElementById('protectSuccessMsg').textContent=`"${file.name||'recording'}" is now protected.`;loadStats();}catch(_){showToast('❌ Cannot reach backend.');}finally{setLoading('protect',false);}}
function setLoading(m,on){document.getElementById(m+'Loader').classList.toggle('active',on);document.getElementById(m+'LoaderTxt').classList.toggle('active',on);const b=m==='detect'?document.getElementById('detectAnalyzeBtn'):m==='protect'?document.getElementById('protectEmbedBtn'):null;if(b)b.disabled=on;}
function downloadReport(){const d=lastResult,lines=['╔══════════════════════════════════════════╗','║      VOICEGUARD FORENSIC REPORT          ║','╚══════════════════════════════════════════╝','',`Generated : ${new Date().toLocaleString()}`,`Analyst   : ${DISPLAY} (@${UNAME})`,'','── AUDIO FILE ─────────────────────────────',`File      : ${d.filename||'—'}`,`Duration  : ${d.duration_seconds?d.duration_seconds+'s':'—'}`,`Sample Rate: ${d.sample_rate?d.sample_rate+' Hz':'—'}`,'','── RESULT ─────────────────────────────────',`Verdict   : ${d.verdict}`,`Auth      : ${d.authenticated?'YES':'NO'}`,`Confidence: ${d.confidence}%`,`FFT Score : ${d.score}`,`Risk      : ${d.risk}`,'','── TECHNICAL ──────────────────────────────','Method    : Fast Fourier Transform (FFT)','Key Bins  : [42,137,256,389,512,701,1024,1337,2048,2500]','Threshold : 1.4','','VoiceGuard v2.0 · OVERCLOCK 24'];const b=new Blob([lines.join('\n')],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`vg_report_${Date.now()}.txt`;a.click();}
const liveRec={recorder:null,chunks:[],blob:null,recording:false,timer:null,elapsed:0};
const BIG_C=452.4,MAX_R=8;
async function toggleLiveRecord(){liveRec.recording?stopLiveRecord():await startLiveRecord();}
async function startLiveRecord(){try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});liveRec.stream=stream;liveRec.chunks=[];liveRec.blob=null;liveRec.elapsed=0;liveRec.recorder=new MediaRecorder(stream,{mimeType:'audio/webm'});liveRec.recorder.ondataavailable=e=>{if(e.data.size>0)liveRec.chunks.push(e.data);};liveRec.recorder.onstop=()=>{liveRec.blob=new Blob(liveRec.chunks,{type:'audio/webm'});stream.getTracks().forEach(t=>t.stop());onLiveDone();};liveRec.recorder.start(100);liveRec.recording=true;const btn=document.getElementById('bigMicBtn');btn.classList.add('recording');btn.classList.remove('done');document.getElementById('bigMicIcon').textContent='⏹️';document.getElementById('recHint').textContent='🔴 Recording… speak clearly';drawBigWave(stream);liveRec.timer=setInterval(()=>{liveRec.elapsed+=.1;document.getElementById('recTimeDisplay').textContent=liveRec.elapsed.toFixed(1)+'s';document.getElementById('bigRingFill').style.strokeDashoffset=BIG_C*(1-Math.min(liveRec.elapsed/MAX_R,1));if(liveRec.elapsed>=MAX_R)stopLiveRecord();},100);}catch(_){showToast('❌ Microphone access denied.');}}
function stopLiveRecord(){if(!liveRec.recording)return;liveRec.recording=false;clearInterval(liveRec.timer);if(liveRec.recorder&&liveRec.recorder.state!=='inactive')liveRec.recorder.stop();}
function onLiveDone(){const btn=document.getElementById('bigMicBtn');btn.classList.remove('recording');btn.classList.add('done');document.getElementById('bigMicIcon').textContent='✅';document.getElementById('recHint').textContent=`${liveRec.elapsed.toFixed(1)}s recorded`;document.getElementById('bigRingFill').style.strokeDashoffset=0;document.getElementById('previewAudio').src=URL.createObjectURL(liveRec.blob);document.getElementById('recordActions').style.display='block';document.getElementById('liveWaveCanvas').style.display='none';}
function drawBigWave(stream){const canvas=document.getElementById('liveWaveCanvas');canvas.style.display='block';const ctx=canvas.getContext('2d'),ac=new AudioContext(),src=ac.createMediaStreamSource(stream),ana=ac.createAnalyser();ana.fftSize=64;src.connect(ana);const data=new Uint8Array(ana.frequencyBinCount);function draw(){if(!liveRec.recording)return;requestAnimationFrame(draw);ana.getByteFrequencyData(data);canvas.width=canvas.clientWidth;canvas.height=48;ctx.clearRect(0,0,canvas.width,canvas.height);const bw=canvas.width/data.length;data.forEach((v,i)=>{const h=(v/255)*canvas.height,g=ctx.createLinearGradient(0,canvas.height-h,0,canvas.height);g.addColorStop(0,'#00e5a0');g.addColorStop(1,'#00e5a020');ctx.fillStyle=g;ctx.fillRect(i*bw,canvas.height-h,bw-1,h);});}draw();}
async function analyzeRecording(){if(!liveRec.blob)return;const rc=document.getElementById('recordResult');rc.className='result-card yellow';rc.style.display='block';rc.innerHTML='<div style="font-family:var(--mono);font-size:.8rem;color:var(--muted);padding:10px">⏳ Analyzing…</div>';const fd=new FormData();fd.append('audio',liveRec.blob,'recording.webm');try{const res=await fetch(`${API}/detect`,{method:'POST',body:fd,headers:authH()}),d=await res.json();lastResult={...d,filename:'live_recording'};showResult(d,'recordResult');loadStats();}catch(_){showToast('❌ Cannot reach backend.');}}
async function protectRecording(){if(!liveRec.blob)return;await runProtect(liveRec.blob);}
function resetRecording(){liveRec.blob=null;liveRec.elapsed=0;document.getElementById('bigMicBtn').classList.remove('recording','done');document.getElementById('bigMicIcon').textContent='🎙️';document.getElementById('recHint').textContent='Click to start recording';document.getElementById('recTimeDisplay').textContent='0.0s';document.getElementById('bigRingFill').style.strokeDashoffset=BIG_C;document.getElementById('recordActions').style.display='none';document.getElementById('recordResult').style.display='none';document.getElementById('liveWaveCanvas').style.display='none';document.getElementById('previewAudio').src='';}
const audioInst={};
async function loadHistory(){try{const res=await fetch(`${API}/history`,{headers:authH()}),rows=await res.json(),tbody=document.getElementById('historyBody');if(!rows.length)return;tbody.innerHTML=rows.map(r=>{const ok=r.verdict==='WATERMARK DETECTED',ha=!!r.stored_filename,ts=new Date(r.timestamp).toLocaleTimeString(),ds=r.duration?r.duration.toFixed(1)+'s':'—';return`<tr><td><div class="hrow-main" onclick="togglePlayer(${r.id},${ha})"><span style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${r.filename}</span><span><span class="verdict-pill ${ok?'ok':'bad'}">${ok?'✅ AUTHENTIC':'❌ TAMPERED'}</span></span><span>${r.confidence}%</span><span style="color:var(--muted)">${ds}</span><span style="color:var(--muted)">${ts}</span><span>${ha?`<button class="play-btn" id="playbtn-${r.id}" onclick="event.stopPropagation();togglePlayer(${r.id},true)">▶ Play</button>`:'<span style="color:var(--muted)">—</span>'}</span></div><div class="player-row" id="player-${r.id}"><div class="audio-player"><div class="player-header"><span class="player-fname">🎵 ${r.filename}</span><span class="player-dur" id="dur-${r.id}">0:00 / ${ds}</span></div><div class="player-ctrl"><button class="ctrl-btn main" id="pp-${r.id}" onclick="togglePlay(${r.id})">▶</button><div class="prog-area"><div class="prog-wrap" onclick="seekAudio(event,${r.id})"><div class="prog-fill" id="pfill-${r.id}"></div><div class="prog-thumb" id="pthumb-${r.id}"></div></div><div class="time-row"><span id="tcur-${r.id}">0:00</span><span id="tend-${r.id}">${ds}</span></div></div><div class="vol-wrap"><span>🔊</span><input type="range" class="vol-slider" min="0" max="1" step="0.05" value="1" oninput="setVol(${r.id},this.value)"></div></div></div></div></td></tr>`;}).join('');}catch(_){}}
function togglePlayer(id,ha){if(!ha)return;const row=document.getElementById(`player-${id}`),open=row.classList.contains('open');document.querySelectorAll('.player-row.open').forEach(r=>{const oid=parseInt(r.id.replace('player-',''));if(oid!==id)closePlayer(oid);});open?closePlayer(id):openPlayer(id);}
function openPlayer(id){document.getElementById(`player-${id}`).classList.add('open');const b=document.getElementById(`playbtn-${id}`);if(b){b.classList.add('playing');b.textContent='■ Close';}loadAudio(id);}
function closePlayer(id){document.getElementById(`player-${id}`)?.classList.remove('open');const b=document.getElementById(`playbtn-${id}`);if(b){b.classList.remove('playing');b.textContent='▶ Play';}stopAudio(id);}
function loadAudio(id){if(audioInst[id])return;const a=new Audio(`${API}/audio/${id}`);a.volume=1;audioInst[id]=a;a.addEventListener('timeupdate',()=>{if(!a.duration)return;const p=(a.currentTime/a.duration)*100,fi=document.getElementById(`pfill-${id}`),th=document.getElementById(`pthumb-${id}`),tc=document.getElementById(`tcur-${id}`),du=document.getElementById(`dur-${id}`);if(fi)fi.style.width=p+'%';if(th)th.style.left=p+'%';if(tc)tc.textContent=ft(a.currentTime);if(du)du.textContent=ft(a.currentTime)+' / '+ft(a.duration);});a.addEventListener('ended',()=>{const pp=document.getElementById(`pp-${id}`);if(pp)pp.textContent='▶';});a.addEventListener('loadedmetadata',()=>{const te=document.getElementById(`tend-${id}`),du=document.getElementById(`dur-${id}`);if(te)te.textContent=ft(a.duration);if(du)du.textContent='0:00 / '+ft(a.duration);});}
function togglePlay(id){const a=audioInst[id];if(!a){loadAudio(id);setTimeout(()=>togglePlay(id),300);return;}const pp=document.getElementById(`pp-${id}`);if(a.paused){Object.entries(audioInst).forEach(([oid,au])=>{if(parseInt(oid)!==id&&!au.paused){au.pause();const ob=document.getElementById(`pp-${oid}`);if(ob)ob.textContent='▶';}});a.play();if(pp)pp.textContent='⏸';}else{a.pause();if(pp)pp.textContent='▶';}}
function stopAudio(id){const a=audioInst[id];if(a){a.pause();a.currentTime=0;}const pp=document.getElementById(`pp-${id}`);if(pp)pp.textContent='▶';}
function seekAudio(e,id){const a=audioInst[id];if(!a||!a.duration)return;const rect=e.currentTarget.getBoundingClientRect();a.currentTime=((e.clientX-rect.left)/rect.width)*a.duration;}
function setVol(id,v){const a=audioInst[id];if(a)a.volume=parseFloat(v);}
function ft(s){if(!s||isNaN(s))return'0:00';return`${Math.floor(s/60)}:${Math.floor(s%60).toString().padStart(2,'0')}`;}
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500);}
